name: Scraping Bot # Nombre del flujo de trabajo

on:
  schedule:
    - cron: '0 * * * *' # Esto significa "cada hora".
  workflow_dispatch: # Permite ejecutar el flujo de trabajo manualmente

# Define el trabajo a realizar.
jobs:
  run-bot:
    runs-on: ubuntu-latest # Elige un ambiente de ejecución, Ubuntu es más común y estable.

    steps:
      # 1. Clona el repositorio en el runner
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala Python en el runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1' # Reemplaza con la versión de Python que uses.

      # 3. Instala las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Configura las credenciales de Firebase
      # - name: Set up Firebase credentials
      #   run: |
      #     echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase_credentials.json
      #   env:
      #     FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      # 5. Ejecuta el bot de scraping
      - name: Run the scraping bot
        run: |
          python index.py  # Reemplaza con el nombre de tu script.
