name: Scraping Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

# Define el trabajo a realizar.
jobs:
  run-bot:
    runs-on: ubuntu-latest # Elige un ambiente de ejecución, Ubuntu es más común y estable.

    steps:
      - name: Set up repository access
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Cambia esto por tu personal access token
        run: echo "Using personal access token"

      # 1. Clona el repositorio en el runner
      - name: Checkout code
        uses: actions/checkout@v3 # No necesitas cambiar la versión, GitHub ya usará Node.js 20

      # 2. Instala Python en el runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1' # Asegúrate de que esta sea la versión de Python que usas.

      # 3. Instala las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta el bot de scraping
      - name: Run the scraping bot
        run: |
          python index.py
