name: Scraping Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

# Define el trabajo a realizar.
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository access
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: echo "Using personal access token"

      # 1. Clona el repositorio en el runner con Node.js 20
      - name: Checkout code
        uses: actions/checkout@v3.1.0 # Versión compatible con Node.js 20

      # 2. Instala Python en el runner con Node.js 20
      - name: Set up Python
        uses: actions/setup-python@v4.7.0 # Versión compatible con Node.js 20
        with:
          python-version: '3.12.1'

      # 3. Instala las dependencias de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta el bot de scraping
      - name: Run the scraping bot
        run: |
          python index.py
